// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI (migrate, studio, db push) siempre usa la conexión directa a
    // Postgres, sin pgbouncer — necesaria para correr DDL. En runtime, la app usa
    // DATABASE_URL (con pooler) desde src/lib/db.ts, no este valor.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
